#!/bin/bash
calc=$1
metrics=( tarantula ochai jaccard dstar )
ps=0
declare -A proj_arr
for proj in */; do
  proj=${proj%/}
  projs[$ps]="$proj"
  ms=0
  cd "$proj"
  for metric in ${metrics[@]}; do
    i=0
    tot=0
    for v in *-fault; do
      cd "$v"
      res=$(python3 $FLITSR_HOME/identify.py "$metric" "$calc")
      tot="$(echo "print($tot+$res)" | python3)"
      ((i++))
      cd ../
    done
    proj_arr[$ps,$ms]="$(echo "print($tot/$i)" | python3)"
    ((ms++))
  done
  ((ps++))
  cd ../
done
for ((j=0;j<ms;j++)) do
  for ((i=0;i<ps;i++)) do
    echo "${projs[i]};${metrics[j]};${proj_arr[$i,$j]}"
  done
done
