#!/bin/bash
#file=$1
for j in 1 2 4 8 16 32; do
  cd "$j-fault"
  for file in *.txt; do
    res=$(python3 ~/subjects/masters/feedback_localizer/find_unex.py "$file")
    if [ "$res" != "" ]; then
      readarray -d   -t arr <<<"$res"
      for fault in $arr; do
        line=$(grep -n -F "$fault" "$file" | cut -f1 -d:)
        sed -i $line"s/ |.*$//" "$file"
      done
      echo "Modified '$file'"
      res=$(python3 ~/subjects/masters/feedback_localizer/find_unex.py "$file")
      if [ "$res" == "no faults found" ]; then
        rm "$file"
        echo "Removed $file (no faults left)"
      fi
    fi
  done
  cd ../
done
