#!/bin/bash
if [ "$2" == "stats" ]; then
  echo "variant, normal, mean, std_dev"
  for metric in tar och jac dst; do
    j=0
    for variant in *.txt; do
      for c in 1 2 3; do
        vals=""
        s=$(($1 - 1))
        for i in {0..$s}; do
          x=$(($j \* 500 + $i \* 5 + $c + 1))
          vals+="$(sed "${x}q;d" "feed_rndm_"$metric"_weff" | sed 's/.*: //g')"$'\n'
        done
        vals=${vals%$'\n'}
        mean="$(echo "$vals" | datamash mean 1)"
        stddev="$(echo "$vals" | datamash pstdev 1)"
        jarque="$(echo "$vals" | datamash jarque 1)"
        echo "$variant-$metric-$c, $jarque, $mean, $stddev"
      done
      j=$(($j + 1))
    done
  done
else
  python3 ~/subjects/masters/feedback_localizer/merge_rndm.py $1
fi
