#!/bin/bash

open_sem() {
  mkfifo pipe-$$
  exec 3<>pipe-$$
  rm pipe-$$
  local i=$1
  for((;i>0;i--)); do
    printf %s 000 >&3
  done
}

run_with_lock() {
  local x
  # this read waits until there is something to read
  read -u 3 -n 3 x && ((0==x)) || exit $x
  (
   ( "$@"; )
  # push the return code of the command to the semaphore
  printf '%.3d' $? >&3
  )&
}

N=8
open_sem $N
for dir in *-fault; do
  cd "$dir"
  if [ ! -f "results" ]; then
    for file in *.txt; do run_with_lock feedback "$file" tcm only_fail all; done
    wait
    for m in tar_ och_ jac_ dst_; do
      for t in "" feed_ feed_tie_ feed_multi_; do
        for file in $t$m*.txt; do
          orig=${file#"$t$m"}
          echo "$orig"
          echo "Using TCM input method"
          cat "$file"; rm "$file";
          echo "--------------------------"
        done > $t$m"weff"
      done
    done
    echo "Done in $dir"
    merge > results
  fi
  cd ../
done
